In [5]:
import numpy as np

In [6]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [7]:
%timeit my_arr2 = my_arr * 2

%timeit my_list2 = [x * 2 for x in my_list]


684 µs ± 14.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
29 ms ± 412 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


For Array, we don't loop, but the function applies as if its dealing with a vector. It enables batch computation.
- An ndarray is a generic multidimensional container for homogeneous data


In [10]:
np.arange? # checking documentation about python objects


SyntaxError: invalid syntax (3070459146.py, line 1)

In [13]:
data = np.array([[1,2,3],[3,3,2]])
data.dtype
data.shape

(2, 3)

In [14]:
# Multiplying and adding
data * 10

array([[10, 20, 30],
       [30, 30, 20]])

In [15]:
# Adding
data + data

array([[2, 4, 6],
       [6, 6, 4]])

A slice creates a view. But you can make a copy with .copy()

In [18]:
d = np.arange(14)
d_s = d[2:4]

In [20]:
d_s

array([2, 3])

In [23]:
d_s[:] = 14
d

array([ 0,  1, 14, 14,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [26]:
d_ss = d_s.copy()
d_ss

array([14, 14])

In [27]:
d_ss == d_s

array([ True,  True])

In [28]:
d_ss is d_s

False

How to access multidimensional array elements?

In [30]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2d[0][2] # 1st level, 2nd level high -> low

3

How you cna quickly test and copy old values back

In [ ]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d[0] = old_values
